### ISSUE TITLE
DemandSidePlatform - opcja wyboru algorytmu do bidowania

### ISSUE THREAD

**Issue by danius0001** [sbobek/DynamicAdvertising#4]
przydała by się opcja wyboru algorytmu bidującego przy uruchamianiu DSP. 

Np. przez podanie nazwy klasy. Później będzie tworzona jej instancja wykorzystując refleksję. W ten sposób obsłużone będą też nowe klasy dodawane przez użytkownika.

**Comment by HrabiaVulpes** [comment]
Taka zdolność została dodane
