### ISSUE TITLE
DEIncomingConnectionHandler - thread pool

### ISSUE THREAD

**Issue by danius0001** [sbobek/DynamicAdvertising#5]
Tutaj podobnie **Executor** nie jest zamykany.

_I tip na przyszłość:_ masz tu listę obiektów **Future** i odbierasz ich wyniki w kolejności występowania na liście. Przez co czekasz na wynik z pierwszego a w tym czasie może jakiś inny się skończyć -> marnuje się w ten sposób czas ;) polecam użycie usługi **ExecutorCompletionService**, która to obsługuje.

**Comment by HrabiaVulpes** [comment]
nie chcę wprowadzać teraz dużych zmian, zwłaszcza że w algorytmie potrzeba mi jakoś powiązać które DSP odesłało odpowiedź z odpowiedzią (dlatego odbieram wyniki w kolejności na liście) a ExecutorCompletionService.take() po prostu zwróci mi pierwsze które odpowiedziało, więc musiałbym wprowadzać jakąś specjalną mechanikę rozpoznawania ich. 

Niemniej zamykanie executora wprowadzone

**Comment by danius0001** [comment]
Spoko, to tylko sugestia na przyszłość ;)
