### ISSUE TITLE
DEIncomingConnectionHandler - wyliczanie secondBest

### ISSUE THREAD

**Issue by danius0001** [sbobek/DynamicAdvertising#6]
_if (bid > bestPrice) {
    secondBest = bestPrice;
    bestPrice = bid;
    bestSocket = socket;
}
if (bid < bestPrice && bid > secondBest) {
    secondBest = bid;
}_

Gdy _bid_ == aktualny _bestPrice_ -> _secondBest_ nie będzie poprawnie wyliczony.
Tak będzie ok:
_if (bid > bestPrice) {
    secondBest = bestPrice;
    bestPrice = bid;
    bestSocket = socket;
} else if (bid > secondBest) {
    secondBest = bid;
}_

**Comment by HrabiaVulpes** [comment]
Rozumiem, poprawka wprowadzona.
